### ISSUE TITLE
Missing Parameters in QGroundControl

### ISSUE THREAD

**Issue by sainikhilmuddam** [rotoye/batmon_reader#1]
I had followed the instructions for PX4 given in README file of https://github.com/rotoye/batmon_reader
But after launching QGroundControl, there is an error stating the following parameters are missing: BAT_SOURCE, BAT_V_LOAD_DROP.
I am using Rotoye Batmon v5.11, connected to the I2C A port of a Pixhawk 4. Tried it with the CAN ports as well, but I'm getting the same result.

Is the documentation provided valid for v5.11? If no, please let me know where I can find the correct instructions.

**Comment by echoGee** [comment]
Please check https://docs.px4.io/master/en/modules/modules_driver.html#batmon for updated docs

**Comment by sainikhilmuddam** [comment]
I have checked the new resources and built the firmware accordingly. But there were a few new issues. 
I compared it to the one done earlier using Rotoye's fork of PX4. 
In the new build, the parameters mentioned in the documentation: BAT_SOURCE and SENS_EN_BAT were present but the BAT_SMBUS_MODEL parameter was missing. 
Can I get some guidance regarding this?
